import { type Sql } from "postgres";

const establishDBConn = async (sql: Sql) => {
  try {
    const conn = await sql`Select 1`;
    console.log("DB connection established correctly");
  } catch (error) {
    throw new Error(
      "Issue while connection to database: " + (error as Error).message,
    );
  }
};


const dbTablesInit = async (sql: Sql) => {
  try {
    console.log("Initializing database tables...");

    await sql`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'company_size') THEN
          CREATE TYPE company_size AS ENUM ('small', 'medium', 'large');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_status') THEN
          CREATE TYPE job_status AS ENUM ('open', 'closed');
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_remote_type') THEN
          CREATE TYPE job_remote_type AS ENUM ('remote', 'hybrid', 'onsite');
        END IF;
      END $$
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS companies (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,        
        name TEXT NOT NULL,
        industry TEXT NOT NULL,
        size company_size NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP      
      )
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS jobs (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,        
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
        salary_max INTEGER,
        salary_min INTEGER CHECK (salary_min <= salary_max),
        status job_status NOT NULL DEFAULT 'open',
        remote_type job_remote_type NOT NULL,
        country TEXT NOT NULL,
        city TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP      
      )
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS skills (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,        
        name TEXT NOT NULL UNIQUE
      )
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS job_skills (
        job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
        skill_id INTEGER NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
        PRIMARY KEY (job_id, skill_id)
      )
    `;
    
    console.log("Database tables verified/created successfully.");
  } catch (error) {
    throw new Error("Error while creating DB tables: " + (error as Error).message);
  }
};

const startDB = async (sql: Sql) => {
  await establishDBConn(sql);
  await dbTablesInit(sql);
}

export default startDB;